//! Walk a `Cargo.lock` and return the crates.io-sourced packages.
//!
//! Path/git/local-registry packages are not on crates.io, so the
//! `rustbert sync` fetch path can't pull them. We classify them out
//! here and let the caller surface a clear "skipped" reason in the
//! plan summary.

use crate::error::Result;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedCrate {
    pub name: String,
    pub version: semver::Version,
}

/// Parse a `Cargo.lock` from a string and keep only the crates.io
/// packages. Workspace members (no `source`) and git/path/registry
/// alternatives are filtered out.
pub fn crates_io_packages_from_str(content: &str) -> Result<Vec<LockedCrate>> {
    let lockfile: cargo_lock::Lockfile = content.parse()?;

    Ok(lockfile
        .packages
        .into_iter()
        .filter_map(locked_crate_from_package)
        .collect())
}

fn locked_crate_from_package(pkg: cargo_lock::Package) -> Option<LockedCrate> {
    let source = pkg.source.as_ref()?;
    if !source.is_default_registry() {
        return None;
    }
    Some(LockedCrate {
        name: pkg.name.as_str().to_string(),
        version: pkg.version,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const LOCK_WITH_MIXED_SOURCES: &str = r#"# autogenerated
version = 4

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"

[[package]]
name = "myapp"
version = "0.1.0"
dependencies = ["serde"]

[[package]]
name = "from-git"
version = "0.2.0"
source = "git+https://github.com/foo/bar?rev=abc123#abc123def4567890123456789012345678901234"
"#;

    #[test]
    fn returns_only_crates_io_packages() {
        let crates = crates_io_packages_from_str(LOCK_WITH_MIXED_SOURCES)
            .expect("lockfile parses");

        let names: Vec<_> = crates.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["serde"]);
        assert_eq!(crates[0].version, semver::Version::new(1, 0, 219));
    }

    #[test]
    fn empty_lockfile_returns_empty() {
        let content = "version = 4\n";
        let crates = crates_io_packages_from_str(content).unwrap();
        assert!(crates.is_empty());
    }

    #[test]
    fn workspace_member_without_source_is_skipped() {
        let content = r#"version = 4

[[package]]
name = "myapp"
version = "0.1.0"
"#;
        let crates = crates_io_packages_from_str(content).unwrap();
        assert!(crates.is_empty());
    }

    #[test]
    fn multiple_crates_io_packages_kept_in_lockfile_order() {
        let content = r#"version = 4

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"

[[package]]
name = "tokio"
version = "1.45.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2222222222222222222222222222222222222222222222222222222222222222"
"#;
        let crates = crates_io_packages_from_str(content).unwrap();
        let names: Vec<_> = crates.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["serde", "tokio"]);
    }

    #[test]
    fn malformed_input_returns_error() {
        let result = crates_io_packages_from_str("not a lockfile");
        assert!(result.is_err());
    }

    #[test]
    fn alternate_registry_source_is_skipped() {
        let content = r#"version = 4

[[package]]
name = "private-thing"
version = "0.1.0"
source = "registry+https://my-private.example/index"
checksum = "3333333333333333333333333333333333333333333333333333333333333333"

[[package]]
name = "serde"
version = "1.0.219"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"
"#;
        let crates = crates_io_packages_from_str(content).unwrap();
        let names: Vec<_> = crates.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(names, vec!["serde"]);
    }

    #[test]
    fn parses_real_workspace_lockfile() {
        // The docbert workspace's own Cargo.lock — the closest
        // realistic fixture available. We don't assert the exact
        // contents (those churn) but every returned entry must be
        // a real, semver-shaped crates.io dep.
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../Cargo.lock");
        let content = std::fs::read_to_string(path)
            .expect("workspace Cargo.lock should exist");
        let crates = crates_io_packages_from_str(&content).unwrap();
        assert!(!crates.is_empty(), "real workspace has crates.io deps");
        for c in &crates {
            assert!(!c.name.is_empty());
        }
    }

    #[hegel::test(test_cases = 30)]
    fn prop_only_crates_io_packages_returned(tc: hegel::TestCase) {
        use hegel::generators as gs;

        // Generate a synthetic lockfile mixing the three source flavors:
        //   0 = workspace member (no source)
        //   1 = crates.io
        //   2 = git
        // The property is that the walker never returns anything other
        // than crates.io entries, regardless of the mix.
        let entry_count: u8 =
            tc.draw(gs::integers::<u8>().min_value(0).max_value(8));

        let mut content = String::from("version = 4\n");
        let mut expected_names: Vec<String> = Vec::new();
        let alphabet = "abcdefghijklmnopqrstuvwxyz";
        let mut used_names = std::collections::HashSet::new();

        for i in 0..entry_count {
            let mut name: String =
                tc.draw(gs::text().alphabet(alphabet).min_size(1).max_size(8));
            // Ensure unique names so the lockfile parses cleanly.
            while !used_names.insert(name.clone()) {
                name.push_str(&format!("_{i}"));
            }

            let major: u64 =
                tc.draw(gs::integers::<u64>().min_value(0).max_value(20));
            let minor: u64 =
                tc.draw(gs::integers::<u64>().min_value(0).max_value(20));
            let patch: u64 =
                tc.draw(gs::integers::<u64>().min_value(0).max_value(20));

            let source_kind: u8 =
                tc.draw(gs::integers::<u8>().min_value(0).max_value(2));

            content.push_str(&format!(
                "\n[[package]]\nname = \"{name}\"\nversion = \"{major}.{minor}.{patch}\"\n",
            ));

            match source_kind {
                0 => {
                    // workspace member — no source line, no checksum
                }
                1 => {
                    content.push_str(
                        "source = \"registry+https://github.com/rust-lang/crates.io-index\"\n",
                    );
                    content.push_str(&format!(
                        "checksum = \"{:0>64}\"\n",
                        i % 9 + 1
                    ));
                    expected_names.push(name);
                }
                _ => {
                    content.push_str(&format!(
                        "source = \"git+https://example.com/{name}?rev=abc123#{:0>40}\"\n",
                        i % 9 + 1
                    ));
                }
            }
        }

        let crates = crates_io_packages_from_str(&content)
            .expect("synthetic lockfile parses");
        let got_names: Vec<&str> =
            crates.iter().map(|c| c.name.as_str()).collect();
        let expected: Vec<&str> =
            expected_names.iter().map(String::as_str).collect();
        assert_eq!(
            got_names, expected,
            "walker returned {got_names:?}, expected {expected:?}",
        );
    }
}
